### ISSUE TITLE
Don't auto-`callPackage`

### ISSUE THREAD

**Issue by roberth** [nixpkgs-architecture/auto-called-packages#6]
The current proposal is rather restrictive when it comes to what's in the files.

We already established that `callPackage` has a number of issues, among which the need for default arguments to live outside the package function, and the package being defined through a function rather than a fixed point in the first place.
By doing a figurative `mapAttrs callPackage` we knowingly paint ourselves into a corner.

**Comment by xaverdh** [comment]
well, we can still add a second fresh directory with different semantics when a decision is made to move away from `callPackage`?

**Comment by roberth** [comment]
From what I understand, moving files en masse leads to many merge conflicts in PRs.
When moving the file, doing a `s/.*/pkgs: pkgs.callPackage (\0) { }/` seems to be worth considering. It also lets us cover packages with non-default arguments.

**Comment by roberth** [comment]
By using `package.nix` as the file name for auto called packages, we have more freedom to reuse the same directory structure while migrating to a more declarative ([functions are a problem](https://github.com/nixpkgs-architecture/issues/wiki/Functions-are-bad-for-overriding)) non-`callPackage` overriding solution. We might want to reserve `package.nix` for the final declarative format though.
